### ISSUE TITLE
Document all settings of the action

### ISSUE THREAD

**Issue by corneliusweig** [rajatjindal/krew-release-bot#24]
For example, the `krew_template_file` setting is undocumented:
```yaml
with:
  krew_template_file: .krew/ns.yaml 
```

Maybe there are even more undocumented features?

**Comment by rajatjindal** [comment]
ack. I will do that.

**Comment by rajatjindal** [comment]
#29 adds the documentation.

**Comment by rajatjindal** [comment]
merged with #29
