### ISSUE TITLE
@ the PR author?

### ISSUE THREAD

**Issue by ahmetb** [rajatjindal/krew-release-bot#43]
We currently say

> ... on behalf of [User](#).

Maybe we should prepend that with @ so that:

1. repo owner gets notified and gets automatically subscribed to the PR
2. no need to construct a link as @$USER gets automatically highlighted + work with various chrome extensions

**Comment by rajatjindal** [comment]
sure, will make this change and push

**Comment by rajatjindal** [comment]
hey @ahmetb , i am making this change, and wanted to see if it will be ok to add 'created by' in the signature of PR body.

something like below (dotted lines excluded):

---

hey krew-index team,

I am @krew-release-bot, and I would like to open this PR to publish version `v1.3.2` of `kubectl-whoami` on behalf of @actor.

Thanks,
krew-release-bot
created with :heart: by @rajatjindal

---

**Comment by corneliusweig** [comment]
Do you really want to get notified for every PR that your bot opens 😉? If you want to have a summary, @krew-release-bot account should already have everything and you have its login, right?

You could also consider to include a link to your repository instead of @-mention yourself. This will also serve as an ad for your personal brand, and is useful for visitors.

**Comment by rajatjindal** [comment]
ok will do that. yes, i do have login for krew release bot account

**Comment by ahmetb** [comment]
> created with ❤️ by @rajatjindal

Ideally we'd want `krew-release-bot` to seem like a semi-official serious project so it would be more professional if you avoid this.

However you can do footers like:

Created-via: https://github.com/rajatjindal/krew-release-bot/
Source-commit: [...]
Source-tag: [...]

or whatever.

**Comment by rajatjindal** [comment]
thanks for your feedback @ahmetb  and @corneliusweig . I've released this as v0.0.38. 

PR example: https://github.com/kubernetes-sigs/krew-index/pull/593

**Comment by rajatjindal** [comment]
to clarify further, it will reflect for people using older version too as the change is on webhook side.
