### ISSUE TITLE
problem with integration in my project: failed to get plugin name from processed template.

### ISSUE THREAD

**Issue by gianarb** [rajatjindal/krew-release-bot#44]
Hello

Thank you for your work but I am having some problem integrating this action in my release workflow. This is the error I currently get described in the repository I am attempting the integration

https://github.com/profefe/kube-profefe/pull/41

This is the currently deployed version of the plugin in [krew-index](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/profefe.yaml)

Do you have any feedback for me?
Thanks

**Comment by gianarb** [comment]
I tried to change /tmp/template-file.yaml with /tmp/profefe.yaml following the idea that plugin file name and plugin name should be the same but no luck.

**Comment by rajatjindal** [comment]
thanks for trying it out and reporting the issue. I will check and get back to you.

**Comment by rajatjindal** [comment]
there is a typo in the file at line https://github.com/profefe/kube-profefe/blob/master/.krew/profefe.yaml#L6

there shouldn't be any space between curly braces

**Comment by rajatjindal** [comment]
You could check the logs here:

- https://github.com/profefe/kube-profefe/actions
- Click on Go Releaser in left navigation
- Click on latest available run
- Click on go releaser in left navigation (again)
- Click on the failing step to see the logs.

(sorry for all the clicks, if I find a link that can point to it directly, i will let u know).

I will wait for you to confirm before closing the issue.

**Comment by rajatjindal** [comment]
> (sorry for all the clicks, if I find a link that can point to it directly, i will let u know).

- go to https://github.com/profefe/kube-profefe
- Click on 'x' sign before 'Latest commit info in the UI.. 
- Click on failing check and further click on failing check.

thanks

**Comment by gianarb** [comment]
It works!! Thanks a lot
