### ISSUE TITLE
Failed to run github action

### ISSUE THREAD

**Issue by corneliusweig** [rajatjindal/krew-release-bot#48]
I tried to set this up for another plugin, but I get the following error:

```
time="2020-11-07T13:09:30Z" level=info msg="using template file \"/github/workspace/.konfig.yaml\""
time="2020-11-07T13:09:30Z" level=info msg="getting sha256 for v0.2.4 bundle.tar.gz (download)"
time="2020-11-07T13:09:31Z" level=info msg="downloaded file /tmp/156726157/1604754570"
time="2020-11-07T13:09:31Z" level=fatal msg="failed to get plugin name from processed template.\nerr: error converting YAML to JSON: yaml: line 8: did not find expected '-' indicator"
```

Link: https://github.com/corneliusweig/konfig/runs/1367721586?check_suite_focus=true

Can you tell what's going on?

**Comment by rajatjindal** [comment]
hey, thanks for using krew-release-bot for the plugin. I opened PR to fix the template: https://github.com/corneliusweig/konfig/pull/30

**Comment by corneliusweig** [comment]
Excellent, thanks for the help. I wonder if you can advertise your tool in a better way. Maybe you can print a hint, if the action fails? This would direct people there who failed to find the helper in the regular way.
