### ISSUE TITLE
Plugin homepage error

### ISSUE THREAD

**Issue by dhiller** [rajatjindal/krew-release-bot#50]
Still trying to release the new version of the kubectl-virt-plugin. Stuck on this error:
https://github.com/kubevirt/kubectl-virt-plugin/runs/1577361409?check_suite_focus=true#step:4:11

Currently my plugin manifest template looks like this, so the error should be resolved no? Or must none of the URLs in the text point towards somewhere else?
https://github.com/kubevirt/kubectl-virt-plugin/blob/master/.krew.yaml#L42

Would appreciate your help on this very much, thanks!

**Comment by rajatjindal** [comment]
Hi @dhiller 

thanks for reaching out. we need to update the home page in 'released version'. https://github.com/kubernetes-sigs/krew-index/blob/e01974f60699a0bf5d84d5256f8b16bc6d0380a2/plugins/virt.yaml#L45 

I tried reaching out to you on kubernetes slack channel but then got sidetracked with other things.

Let me know if you have more questions, happy to answer. and sorry for all the trouble.

**Comment by dhiller** [comment]
Ah! So IIUC the error is not on our side? Can I just create a PR against the virt.yaml you pointed to and fix this myself?

**Comment by rajatjindal** [comment]
yeah, once you fix that homepage value in virt.yaml in krew-index repo, then krew-release-bot will (should :) ) open the PR for next release correctly.

**Comment by corneliusweig** [comment]
maybe it would sense to add a configuration option for the case where the referenced repo is not the repo where the code is stored? In general this should not happen often, but this case seems legitimate.

**Comment by rajatjindal** [comment]
hi @corneliusweig 

thank you for your feedback. let me think a little bit about it (the validation, the requirement for this validation and its usefulness) and get back to you.

thanks

**Comment by rajatjindal** [comment]
ok, removed this validation as it was causing grief and providing no value. 

released v0.0.39 of krew-release-bot
