### ISSUE TITLE
opening pr: authentication required

### ISSUE THREAD

**Issue by kei6u** [rajatjindal/krew-release-bot#61]
@rajatjindal I am a user of this amazing tool. I appreciate your work.

I got the error below.

```
time="2022-01-20T13:38:29Z" level=fatal msg="expected status code 200 got 500. body: opening pr: authentication required"
```

I haven't changed the configuration since it worked fine with GitHub Actions.
My configuration of GitHub Actions here.
https://github.com/kei6u/kubectl-explore/blob/7a6942bbb41875ff330bb02aae76487e169209da/.github/workflows/release.yaml#L1-L24

Could you look into this case?

**Comment by fleeto** [comment]
I'm facing the same problem and now I can only update the index manually, is there any solution?

**Comment by rajatjindal** [comment]
Thanks for reporting the issue. I will check as soon as i have access to laptop. 

We fixed something similar few days back (we believe it was a github token issue, and reported a github ticket for the same).

Thanks

**Comment by rajatjindal** [comment]
it seems like an issue with go-git or github. i am still trying to find a workaround:

this is the error i see in logs when trying to push the code via go-git: 

```bash
doing push: unexpected client error: unexpected requesting "https://github.com/krew-release-bot/krew-index.git/info/refs?service=git-receive-pack" status code: 400
```

**Comment by rajatjindal** [comment]
ok, this is all my fault. last time similar issue happened, and I generated a new token for the bot. But somehow I set the expiration to one month :(

i've generated the new token with "no expiration" and redeployed the bot.

apologies for all the pain this caused.

**Comment by kei6u** [comment]
@rajatjindal Thanks for your quick response!
