### ISSUE TITLE
add end-to-end examples

### ISSUE THREAD

**Issue by ahmetb** [rajatjindal/krew-release-bot#7]
Link to examples people can copy paste, e.g.

- Example: **kubectl-whoami** plugin (Go) - [.krew.yml](#) - [Github Workflow](#)
- Example: **kubectl-tree** plugin (Go) - [.krew.yml](#) - [Github Workflow](#)
- Example: (maybe a bash based example)

**Comment by rajatjindal** [comment]
the examples were added to readme file
