### ISSUE TITLE
Bump github.com/google/go-github

### ISSUE THREAD

**Issue by guessi** [rajatjindal/krew-release-bot#70]
Currently the package `github` was [pinned](https://github.com/rajatjindal/krew-release-bot/blob/v0.0.44/go.mod#L7) to `v29.0.3` which was released back at [Feb 11, 2020](https://github.com/google/go-github/releases/tag/v29.0.3) - 3 years ago.

- https://github.com/rajatjindal/krew-release-bot/blob/v0.0.44/go.mod#L7
- https://github.com/rajatjindal/krew-release-bot/blob/v0.0.44/pkg/releaser/git.go#L9
- https://github.com/rajatjindal/krew-release-bot/blob/v0.0.44/pkg/source/actions/webhook.go#L11
- https://github.com/rajatjindal/krew-release-bot/blob/v0.0.44/pkg/source/actions/action_runner.go#L13
- https://github.com/rajatjindal/krew-release-bot/blob/v0.0.44/vendor/modules.txt#L35-L38
- https://github.com/rajatjindal/krew-release-bot/tree/v0.0.44/vendor/github.com/google/go-github/v29

Maybe it could be bump to `v50+` for getting bug fixes, new features?
- https://github.com/google/go-github/releases

```bash
$ sed -i "" -e 's/v29 v29.0.3/v50 v50.2.0/g' go.mod
$ sed -i "" -e 's/v29/v50/g' pkg/releaser/git.go
$ sed -i "" -e 's/v29/v50/g' pkg/source/actions/webhook.go
$ sed -i "" -e 's/v29/v50/g' pkg/source/actions/action_runner.go
$ go mod vendor
$ go mod tidy
```

**Comment by rajatjindal** [comment]
thank you for reporting this. I have now updated the `go-github` dependency.
